### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Jeanoo** [filipizydorczyk/next-cloud-deck-backup#1]
Hello
can you help me to save my deck cards?
I can pay for it. 

Thanks

**Comment by filipizydorczyk** [comment]
Hello!
There is no need to pay for it xD
You can basically just use this script. Do you want to save it once or do regural backup? Also do you run windows, linux or mac?

**Comment by Jeanoo** [comment]
thank you very much
I am on a windows pc and I have nextcloudpi on a raspberry pi 4
it seems that I have problems in my instance and I would like to reinstall it without losing the deck cards.
My nextcloudpi backup seems to be corrupted, so I need to be able to restore all my cards.

**Comment by filipizydorczyk** [comment]
Okey got it. So to download your decks you need to clone this repo (and I am assuming that you have python and pip installed) and install dependencies. On windows you can do this by `pip install -r requirements.txt`. Then you need to call python script providing information about ur instance (url, username, password)

```
python ./main.py --host "$NEXTCLOUD_HOST" --username "$NEXTCLOUD_USER" --passwd "$NEXTCLOUD_PASSWORD" --directory /path/where/you/want/to/save/json
```

Once you do that you should have .json file with all of the data in it. 

Before you will reinstall you might want to test it on other instance if sending script works. I didn't have any issue with that but my nextcloud isntance is also outdated so I can not guarantee anything. So make test nextcloud instance on ur localhost and try send ur json there. You do this same way as saving data but u add `--mode send`

```
python ./main.py --host "$NEXTCLOUD_HOST" --username "$NEXTCLOUD_USER" --passwd "$NEXTCLOUD_PASSWORD" --directory /path/where/you/want/to/save/json --mode send
```
If it works you can probably reinstall yuor nextcloud and do this one more time on your actual instance.
If anything I wrote is confusing dont hesitate to ask more questions :D

**Comment by Jeanoo** [comment]
Hello,
thank you for your help
Let's start at the beginning.
where should this be installed? 
"and I am assuming that you have python and pip installed) and install dependencies"

**Comment by filipizydorczyk** [comment]
You need python and some packages to run this script. Location doesnt matter its just like any other software you install.
You can install python from here: https://www.python.org/downloads/
And also you will need pip for package install. I am not sure if python comes with pip by default. You can follow this tutorial: https://www.liquidweb.com/kb/install-pip-windows/ to check if pip is installed and to install if thats not a case. You will have to user commandline for that

**Comment by Jeanoo** [comment]
Hello,
I installed python 3.10, the package contained pip.
But when I type python on CMD (as shown in the video https://www.liquidweb.com/kb/install-pip-windows/ ) the Microsoft app store opens to install it, strange.  

Can you give me the next steps, please?

N.B.: Sorry for the delay, I couldn't answer earlier

**Comment by Jeanoo** [comment]
Hello,
I installed python 3.10, the package contained pip.
But when I type python on CMD (as shown in the video https://www.liquidweb.com/kb/install-pip-windows/ ) the Microsoft app store opens to install it, strange.  

Can you give me the next steps, please?

N.B.: Sorry for the delay, I couldn't answer earlier

**Comment by filipizydorczyk** [comment]
Here you have stackoverflow that shows how to fix that: https://stackoverflow.com/questions/58754860/cmd-opens-window-store-when-i-type-python.
If u did steps from my previous comment and have python and pip installed you can either clone or download this repository, got to the project in terminal and type this to install needed python packages

```
pip install -r requirements.txt
```

Than you can run this command and replace arguments with yours

```
 python ./main.py --host https://yornextcloud --username uer-username --passwd your-password --directory /path/where/save/json
```

At this point you should have json file with your decks in path u provided `/path/where/save/json`. You can go in file explorer to place where you want to save it and copy location from input at the very top

**Comment by Jeanoo** [comment]
Thank you for your help 
for the moment I have not managed to correct the problem, I am looking for...

**Comment by Jeanoo** [comment]
Now on cmd (terminal), #I have the following result  Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

Python seems to be well established 

about, 
`pip install -r requirements.txt `
I don't know how to do 
I run it on the CMD terminal? 

Thanks

**Comment by filipizydorczyk** [comment]
Yes you can run it in cmd or powershell. Just navigate to project directory and run this command

**Comment by Jeanoo** [comment]
I have this error
C:\Users\Jean\Documents\ncp>pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the 'C:\Users\Jean\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

Do I need to create a text file on the folder where I will receive the tasks?
What should this file contain?

**Comment by filipizydorczyk** [comment]
Are you in project directory when you call this command?

**Comment by Jeanoo** [comment]
I don't understand what this project category is.
I created an empty folder, and ran the command in that folder  (ncp) C:\Users\Jean\Documents\ncp>

**Comment by filipizydorczyk** [comment]
It project directory (or folder), not category. If you created empty directory it will not work because it needs file `requirements.txt` which is part of this repository. If you dont have that file your command will fail. I dont know if you have git installed if yes you can just colne this repo otherwise github allows you to dowlnoad code with a button. When you have this project on your pc open it in your cmd and type that command

**Comment by Jeanoo** [comment]
Ok! I created the requirements.txt file on the ncp folder C:\Users\Jean\Documents\ncp
I moved to the ncp folder with the cd command
and ran `pip install -r requirements.txt `
no message appeared on the terminal 
then I executed the order with my personal information 
`python ./main.py --host https://yornextcloud --username uer-username --passwd your-password --directory /path/where/save/json`
error 
python: can't open file 'C:\\Users\\Jean\\Documents\\ncp\\main.py': [Errno 2] No such file or directory

**Comment by filipizydorczyk** [comment]
Thats not what I told u to do. You were not suppose to create new file but clone this repository (or download it) and open it in your cmd. If you do this you will have both files - `requirements.txt`  and `main.py`. There is no need to create any files. Try again with downloading this project

**Comment by Jeanoo** [comment]
Sorry, I didn't quite understand, because of all the little problems I had. 

It's ok, I succeeded in installing it
```
C:\Users\Jean\Documents\ncp>pip install -r requirements.txt
Collecting pyinstaller
  Downloading pyinstaller-5.1-py3-none-win_amd64.whl (1.2 MB)
     ---------------------------------------- 1.2/1.2 MB 5.2 MB/s eta 0:00:00
Collecting progress
  Downloading progress-1.6.tar.gz (7.8 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in c:\users\Jean\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller->-r requirements.txt (line 1)) (58.1.0)
Collecting pefile>=2017.8.1
  Downloading pefile-2022.5.30.tar.gz (72 kB)
     ---------------------------------------- 72.9/72.9 kB 2.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting altgraph
  Downloading altgraph-0.17.2-py2.py3-none-any.whl (21 kB)
Collecting pyinstaller-hooks-contrib>=2021.4
  Downloading pyinstaller_hooks_contrib-2022.7-py2.py3-none-any.whl (234 kB)
     ---------------------------------------- 234.3/234.3 kB 4.8 MB/s eta 0:00:00
Collecting pywin32-ctypes>=0.2.0
  Downloading pywin32_ctypes-0.2.0-py2.py3-none-any.whl (28 kB)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
     ---------------------------------------- 829.2/829.2 kB 4.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for progress, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pefile, since package 'wheel' is not installed.
Using legacy 'setup.py install' for future, since package 'wheel' is not installed.
Installing collected packages: pywin32-ctypes, progress, altgraph, pyinstaller-hooks-contrib, future, pefile, pyinstaller
  Running setup.py install for progress ... done
  Running setup.py install for future ... done
  Running setup.py install for pefile ... done
Successfully installed altgraph-0.17.2 future-0.18.2 pefile-2022.5.30 progress-1.6 pyinstaller-5.1 pyinstaller-hooks-contrib-2022.7 pywin32-ctypes-0.2.0
```
Now I have another mistake, here it is: 
```
C:\Users\Jean\Documents\ncp>python ./main.py --host "******" --username "*****" --passwd "*****" --directory C:\Users\Jean\Documents\ncp\filles
Traceback (most recent call last):
  File "C:\Users\Jean\Documents\ncp\main.py", line 1, in <module>
    from utils import DeckDownloader, DeckSender, ProgressListener
  File "C:\Users\Jean\Documents\ncp\utils.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Thanks

**Comment by filipizydorczyk** [comment]
Okey it seems like `requests` is also module that need to be installed. I probably already had this module alredy installed and didnt put this package to `requirements.txt` file.

Please try `pip install requests` and try again.

**Comment by Jeanoo** [comment]
result 
`C:\Users\Jean\Documents\ncp>pip install -r requirements.txt
Requirement already satisfied: pyinstaller in c:\users\Jean\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (5.1)
Requirement already satisfied: progress in c:\users\Jean\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 2)) (1.6)
Requirement already satisfied: pefile>=2017.8.1 in c:\users\Jean\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller->-r requirements.txt (line 1)) (2022.5.30)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\users\Jean\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller->-r requirements.txt (line 1)) (0.2.0)
Requirement already satisfied: setuptools in c:\users\Jean\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller->-r requirements.txt (line 1)) (58.1.0)
Requirement already satisfied: altgraph in c:\users\Jean\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller->-r requirements.txt (line 1)) (0.17.2)
Requirement already satisfied: pyinstaller-hooks-contrib>=2021.4 in c:\users\Jean\appdata\local\programs\python\python310\lib\site-packages (from pyinstaller->-r requirements.txt (line 1)) (2022.7)
Requirement already satisfied: future in c:\users\Jean\appdata\local\programs\python\python310\lib\site-packages (from pefile>=2017.8.1->pyinstaller->-r requirements.txt (line 1)) (0.18.2)`

`C:\Users\Jean\Documents\ncp>python ./main.py --host "*******" --username "******" --passwd "*******" --directory C:\Users\Paulo\Documents\ncp\filles
Traceback (most recent call last):
  File "C:\Users\Jean\Documents\ncp\main.py", line 1, in <module>
    from utils import DeckDownloader, DeckSender, ProgressListener
  File "C:\Users\Jean\Documents\ncp\utils.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

I'm sorry but I don't understand why it doesn't work

**Comment by filipizydorczyk** [comment]
Did u try running `pip install requests` as I said? Because logs looks like u didnt

**Comment by Jeanoo** [comment]
sorry, I had done  `pip install -r requirements.txt`
now it's okay
Many thanks for your patience
Thank you for your patience, I now have a nextcloud-decks.json file  
is it possible to see the contents of the  .json

**Comment by Jeanoo** [comment]
It's ok, I opened it with firefox.
Thanks again

**Comment by filipizydorczyk** [comment]
No problem!

**Comment by Jeanoo** [comment]
`--mode send`
One last question please
When sending, if the instance already contains decks are they replaced or duplicates created?

**Comment by filipizydorczyk** [comment]
If you alredy have some decks created it will create duplicates. You can alwyas delete duplicates later

**Comment by Jeanoo** [comment]
ok! thank you very much
